# Cache headers for rupee.png file
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/rupee.png"
    [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    cache-control = '''
	max-age=31104000,
	public,
	must-revalidate'''

# Cache header for manifest.json file
[[headers]]
  for = "/manifest.json"
    [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    cache-control = '''
    max-age=31104000,
    public,
    must-revalidate'''

# Redirect all requests to index.html
[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
  force = true