name: Lighthouse Score
on:
  pull_request:
    branches: [ master ]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        env:
          cache-name: node-modules-yarn
          cache-fingerprints: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.node-modules-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          lhci autorun
