name: Lint PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        env:
          cache-name: node-modules-yarn
          cache-fingerprints: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.node-modules-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}


      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Run Linter
        run: yarn run lint
