name: Pull Request Checks

on:
  pull_request:
    branches:
      - master # You can customize this based on your branch naming convention

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = "Please make sure to mark the checkboxes in the conversation.";
            
            await github.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body,
            });

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR conversation
        run: |
          REPOSITORY=${GITHUB_REPOSITORY}
          PR_NUMBER=${{ github.event.number }}

          # Fetch comments on the pull request
          COMMENTS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${REPOSITORY}/issues/${PR_NUMBER}/comments")

          # Check if specific checkboxes are marked in the comments
          checkboxes=("Tested the code locally" "Not added any image locally")

          checkboxes_found=true

          for checkbox in "${checkboxes[@]}"; do
            if ! echo "$COMMENTS" | jq -r '.[].body' | grep -q "\[x\] $checkbox"; then
              checkboxes_found=false
              break
            fi
          done

          if $checkboxes_found; then
            echo "All required checkboxes are ticked. Proceeding..."
          else
            echo "Some required checkboxes are not ticked. Please update the PR conversation."
            exit 1
          fi
  
