name: Pull Request Checks

on:
  pull_request:
    branches:
      - master # You can customize this based on your branch naming convention

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR template
        run: |
          if grep -q -E '^\s*- \[x\] Tested the code locally' .github/PULL_REQUEST_TEMPLATE.md &&
            grep -q -E '^\s*- \[x\] Not added any image locally' .github/PULL_REQUEST_TEMPLATE.md; then
          echo "All required checkboxes are ticked. Proceeding..."
          else
          echo "Some required checkboxes are not ticked. Please update the PR template."
          exit 1
          fi

