name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch PR details
        id: fetch-pr
        run: |
          PR_DETAILS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}")

          if [ -z "${PR_DETAILS}" ]; then
            echo "Failed to fetch PR details."
            exit 1
          else
            echo "Fetched PR Details:"
            echo "${PR_DETAILS}"
          fi

          # Extract the body from PR_DETAILS and store it in a variable
          PR_BODY=$(echo "$PR_DETAILS" | jq -r .body)
          echo "PR_BODY=${PR_BODY}" # This line is optional but can help debug

      - name: Echo PR body
        run: |
          PR_BODY="${{ steps.fetch-pr.outputs.pr-details | fromJSON | .body }}"
          echo "Fetched PR Body:"
          echo "$PR_BODY"

      - name: Check PR conversation
        run: |
          # Check if specific checkboxes are marked in the comments
          checkboxes=("Tested the code locally" "Not added any image locally")

          checkboxes_found=true

          for checkbox in "${checkboxes[@]}"; do
            if ! echo "$PR_BODY" | grep -q "\[x\] $checkbox"; then
              checkboxes_found=false
              break
            fi
          done

          if $checkboxes_found; then
            echo "All required checkboxes are ticked. Proceeding..."
          else
            echo "Some required checkboxes are not ticked. Please update the PR conversation."
            exit 1
          fi
