name: update-branch
on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Update Git pr having base branch master
        run: node ./autoupdate.js
